name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  check:
    name: Lint / Typecheck / Test / Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Show versions
        run: |
          bun --version

      - name: Install dependencies
        run: bun install --frozen-lockfile || bun install

      - name: Biome check
        run: bunx --yes biome@latest check .

      - name: Typecheck
        run: bun run typecheck || bunx --yes typescript tsc --noEmit

      - name: Test
        run: bun test

      - name: Build
        run: bun run build || echo "build script not yet defined"

      - name: JSR dry-run
        run: bun run jsr:check

  publish:
    name: Publish to JSR (main branch)
    needs: check
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile || bun install

      - name: Publish (JSR)
        run: bunx --yes jsr publish

